name: Requested Reviewers
on:
  pull_request:
    branches: [main]
    types: [opened, reopened]
env:
  ARTIFACT_NAME: 'requestedReviewersArtifact'
jobs:
  requestedCodeowners:
    name: Get Requested Reviewers on PR open
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository to get the workflow scripts
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      - name: Save the requested reviewers from PR open
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410
        id: requested-reviewers
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            const { getRequestedReviewers } = require('./.github/workflows/scripts/requested_reviews.js');
            return getRequestedReviewers({github, context});
      - name: Create artifact containing PR number and list of requested reviewers
        run: |
          artifactName="${{ env.ARTIFACT_NAME }}.txt"
          echo $'${{ steps.requested-reviewers.outputs.result }}' >> $artifactName
      - name: Upload the file to artifacts
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
        with:
          name: '${{ env.PR_NUMBER }}_${{ env.ARTIFACT_NAME }}'
          path: '${{ env.ARTIFACT_NAME }}.txt'
