name: Verify Approvers
on:
  pull_request_review:
    types: [submitted]
env:
  ARTIFACT_NAME: 'requestedReviewersArtifact'
jobs:
  verifyApproval:
    name: Verify approvals
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get requested reviewers artifact
        uses: actions/github-script@v6.4.0
        env:
          WORKSPACE: ${{ github.workspace }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { getRequstedReviewers } = require('./.github/workflows/scripts/verify_approvers.js');
            const fs = require('fs');
            const artifactName = process.env.ARTIFACT_NAME;
            const prNumber = process.env.PR_NUMBER;
            const workspace = process.env.WORKSPACE
            getRequstedReviewers({github, context, fs, workspace, artifactName, prNumber});
      - name: Unzip artifact
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: unzip '${{ env.PR_NUMBER }}_${{ env.ARTIFACT_NAME }}.zip'
      - name: Verify approvers
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410
        env:
          WORKSPACE: ${{ github.workspace }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const {  }
