name: Verify Approvers
on:
  pull_request_review:
    types: [submitted]
env:
  ARTIFACT_NAME: 'requestedReviewers'
jobs:
  verifyApproval:
    name: Verify approvals
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Verify approvers
        uses: actions/github-script@v6.4.0
        env:
          WORKSPACE: ${{ github.workspace }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { verifyApprovers } = require('./.github/workflows/scripts/verify_approvers.js');
            const fs = require('fs');
            const artifactName = process.env.ARTIFACT_NAME;
            const prNumber = process.env.PR_NUMBER;
            verifyApprovers({github, context, artifactName, prNumber});
